<?php
if ($year) {
    if ($month) {
        $title = 'Archief van ' . date('F', mktime(0, 0, 0, $month, 1, $year)) . ' ' . $year;
    } else {
        $title = 'Archief van ' . $year;
    }
} else {
    $title = 'Archief';
}
$this->setGlobal('title', $title);
?>

<div class="grid">
    <div class="eight wide column">
        <div class="two blocks">
            <?php include 'articles.phtml'; ?>
        </div>

        <?php if (isLoggedIn()): ?><div class="bottomlinks"><a href="/edit">Nieuwe blog</a></div><?php endif; ?>
    </div>

    <div class="three wide column sidebar">
        <?php include 'archivelist.phtml'; ?>
    </div>
</div>
