<?php
if ($year) {
    if ($month) {
        $title = 'Archief van ' . date('F', mktime(0, 0, 0, $month, 1, $year)) . ' ' . $year;
    } else {
        $title = 'Archief van ' . $year;
    }
} else {
    $title = 'Archief';
}
$this->setGlobal('title', $title);
?>

<div class="grid">
    <div class="eight wide column">
        <div class="two blocks">
            <?php foreach ($articles as $article): ?>
                <a class="block" href="/<?= $article['slug'] ?>">
                    <h2 class="headline"><?= $article['title'] ?></h2>
                    <p class="lead"><?= $article['lead'] ?></p>
                    <div class="date"><?= strftime('%e %B %Y', strtotime($article['published'])) ?></div>
                    <div class="readmore">Lees meer</div>
                </a>
            <?php endforeach; ?>
        </div>

        <?php if (isLoggedIn()): ?><div class="bottomlinks"><a href="/edit">Nieuwe blog</a></div><?php endif; ?>
    </div>

    <div class="three wide column sidebar">
        <?php include 'archivelist.phtml'; ?>
    </div>
</div>
