<?php
if ($year) {
    if ($month) {
        $title = 'Archief van ' . date('F', mktime(0, 0, 0, $month, 1, $year)) . ' ' . $year;
    } else {
        $title = 'Archief van ' . $year;
    }
} else {
    $title = 'Archief';
}
$this->setGlobal('title', $title);
?>

<div class="grid">
    <div class="eight wide column">
        <div class="two blocks">
            <?php foreach ($articles as $article): ?>
                <a class="block" href="/<?= $article['slug'] ?>">
                    <h2 class="headline"><?= $article['title'] ?></h2>
                    <p class="lead"><?= $article['lead'] ?></p>
                    <div class="date"><?= strftime('%e %B %Y', strtotime($article['published'])) ?></div>
                    <div class="readmore">Lees meer</div>
                </a>
            <?php endforeach; ?>
        </div>

        <?php if (isLoggedIn()): ?><div class="bottomlinks"><a href="/edit">Nieuwe blog</a></div><?php endif; ?>
    </div>

    <div class="three wide column sidebar">
        <h3 class="headline">Archief</h3>

        <h4 class="subheader">Per maand</h4>
        <ul class="navigation">
            <?php foreach ($archiveList as $y => $yearData): ?>
                <?php foreach ($yearData['months'] as $m => $monthData): ?>
                    <li class="<?= ($m == $month && $y == $year) ? 'active ' : '' ?>item"><a href="/archive/<?= $y ?>/<?= $m ?>"><?= $monthData['name'] ?> <?= $year ?> (<?= $monthData['count'] ?>)</a></li>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </ul>

        <h4 class="subheader">Per categorie</h4>
        <ul class="navigation">
            <?php foreach ($categories as $cat): ?>
                <li class="<?= ($cat['id'] == $category['id']) ? 'active ' : '' ?>item"><a href="/<?= $cat['slug'] ?>"><?= $cat['name'] ?> (<?= $cat['count'] ?>)</a></li>
            <?php endforeach; ?>
        </ul>

    </div>
</div>
