<?php $layout->title = $category['name']; ?>

<div class="grid">
    <div class="eight wide column">
        <div class="two blocks">
            <?php foreach ($articles as $article): ?>
                <a class="block" href="/<?= $article['slug'] ?>">
                    <h2 class="headline"><?= $article['title'] ?></h2>
                    <p class="lead"><?= $article['lead'] ?></p>
                    <div class="date"><?= strftime('%e %B %Y', strtotime($article['published'])) ?></div>
                    <div class="readmore">Lees meer</div>
                </a>
            <?php endforeach; ?>
        </div>

        <?php if ($pagination['page_count'] > 1): ?>
        <nav class="pagination">
            <?php if ($pagination['current'] > $pagination['first']): ?><a class="next item">&laquo; Vorige pagina</a><?php endif; ?>
            <?php for ($page = $pagination['first']; $page <= $pagination['last']; $page++): ?>
                <a href="?page=<?= $page ?>" class="<?= ($page == $pagination['current']) ? 'active ' : '' ?>item"><?= $page ?></a>
            <?php endfor; ?>
            <?php if ($pagination['current'] < $pagination['last']): ?><a class="next item">Volgende pagina &raquo;</a><?php endif; ?>
        </nav>
        <?php endif; ?>

        <p><a href="/edit">New article</a></p>
    </div>

    <div class="three wide column sidebar">
        <h3 class="headline">Archief</h3>

        <h4 class="subheader">Per maand</h4>
        <ul class="navigation">
            <?php foreach ($archiveList as $year => $yearData): ?>
                <?php foreach ($yearData['months'] as $month => $monthData): ?>
                    <li class="item"><a href="/archive/<?= $year ?>/<?= $month ?>"><?= $monthData['name'] ?> <?= $year ?> (<?= $monthData['count'] ?>)</a></li>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </ul>

        <h4 class="subheader">Per categorie</h4>
        <ul class="navigation">
            <?php foreach ($categories as $cat): ?>
                <li class="<?= ($cat['id'] == $category['id']) ? 'active ' : '' ?>item"><a href="/<?= $cat['slug'] ?>"><?= $cat['name'] ?> (<?= $cat['count'] ?>)</a></li>
            <?php endforeach; ?>
        </ul>

    </div>
</div>
