<?php $layout->title = 'Schrijf een eind op'; ?>

<div class="article">
    <h2>Als je het niet zeggen kan...</h2>

    <p class="lead">Schrijf dan een eind op. Dat is niet per se mijn motto, maar wel een leuke uitspraak.
    Ik ben Wubbo en dit is mijn 'blog'. Hier schrijf ik over dingen die mij bezig houden of die zomaar
    bij mij boven komen.</p>
</div>

<hr/>

<div class="grid">
    <div class="eight wide column">
        <div class="two blocks">
            <?php foreach ($articles as $article): ?>
                <a class="block" href="/<?= $article['slug'] ?>">
                    <h2 class="headline"><?= $article['title'] ?></h2>
                    <p class="lead"><?= $article['lead'] ?></p>
                    <div class="date"><?= strftime('%e %B %Y', strtotime($article['published'])) ?></div>
                    <div class="readmore">Lees meer</div>
                </a>
            <?php endforeach; ?>
        </div>

        <?php if ($pagination['page_count'] > 1): ?>
        <nav class="pagination">
            <?php if ($pagination['current'] > $pagination['first']): ?><a class="next item">&laquo; Vorige pagina</a><?php endif; ?>
            <?php for ($page = $pagination['first']; $page <= $pagination['last']; $page++): ?>
                <a href="?page=<?= $page ?>" class="<?= ($page == $pagination['current']) ? 'active ' : '' ?>item"><?= $page ?></a>
            <?php endfor; ?>
            <?php if ($pagination['current'] < $pagination['last']): ?><a class="next item">Volgende pagina &raquo;</a><?php endif; ?>
        </nav>
        <?php endif; ?>

        <?php if (isLoggedIn()): ?><div class="bottomlinks"><a href="/edit">Nieuwe blog</a></div><?php endif; ?>
    </div>

    <div class="three wide column sidebar">
        <h3 class="headline">Archief</h3>

        <h4 class="subheader">Per maand</h4>
        <ul class="navigation">
            <?php foreach ($archiveList as $year => $yearData): ?>
                <?php foreach ($yearData['months'] as $month => $monthData): ?>
                    <li class="item"><a href="/archive/<?= $year ?>/<?= $month ?>"><?= $monthData['name'] ?> <?= $year ?> (<?= $monthData['count'] ?>)</a></li>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </ul>

        <h4 class="subheader">Per categorie</h4>
        <ul class="navigation">
            <?php foreach ($categories as $category): ?>
                <li class="item"><a href="/<?= $category['slug'] ?>"><?= $category['name'] ?> (<?= $category['count'] ?>)</a></li>
            <?php endforeach; ?>
        </ul>

    </div>
</div>
