<h1>Blogin</h1>

<?php if ($error): ?>
    <div style="color:red"><?= $error ?></div>
<?php endif; ?>

<form method="post" action="/login">
    <p>
        <label for="login_username">Username:</label><br/>
        <input type="text" name="username" id="login_username" value="<?= $username ?>" />
    </p>
    <p>
        <label for="login_password">Password:</label><br/>
        <input type="password" name="password" id="login_password" value="" />
    </p>
    <p>
        <button type="submit">Login</button>
    </p>
</form>