<?php $this->setGlobal('title', $article['title']); ?>

<?php if (!empty($article['image_url'])) $this->setGlobal('headerImage', $article['image_url']); ?>

<?php $this->startCapture('meta', true); ?>
    <meta property="og:title" content="<?= $article['title'] ?>" />
    <meta property="og:type" content="article" />
    <meta property="og:description" content="<?= $article['lead'] ?>" />
    <?php if ($article['image_url']): ?>
    <meta property="og:image" content="<?= 'http://' . $_SERVER['HTTP_HOST'] . $article['image_url'] ?>" />
    <?php endif; ?>
<?php $this->endCapture(); ?>

<div class="grid">
    <div class="eight wide column">

        <article class="article">
            <div class="date"><?= strftime('%e %B %Y', strtotime($article['published'])) ?></div>

            <?= $article['content'] ?>


            <div class="sharebar">
                Deel dit artikel:
                <?php $url = 'http://' . $_SERVER['HTTP_HOST'] . '/' . $article['slug']; ?>
                <a href="https://www.facebook.com/sharer/sharer.php?u=<?= urlencode($url) ?>" target="_blank" class="facebook share link" title="Deel dit artikel op Facebook"><i class="facebook icon"></i></a>
                <a href="https://twitter.com/home?status=<?= urlencode($article['title'].' '.$url) ?>&via=schrijfwub" target="_blank" class="twitter share link" title="Deel dit artikel op Twitter"><i class="twitter icon"></i></a>
            </div>

            <div class="bottomlinks">
                <a href="/">Terug naar overzicht</a>
                <?php if (isLoggedIn()): ?> - <a href="/edit/<?= $article['slug'] ?>">Bewerken</a><?php endif; ?>
            </div>

        </article>

        <div class="comments">
            <h3 class="headline">4 comments</h3>

            <h4 class="subheader">Schrijf een reactie</h4>

            <form class="" id="comment_form">
                <div class="form_logged_in">
                    <input type="hidden" name="commenter_key" />
                    <div class="meta">Plaats een reactie als <a href="/" class="author" id="commenter_name"></a> (<span id="commenter_email"></span>) <span class="divider">&bull;</span> <a href="/" class="author" id="change_commenter">Wijzigen</a></div>
                </div>

                <div class="input">
                    <label for="comment_comment">Wat is hierop je reactie?</label>
                    <textarea id="comment_comment"></textarea>
                </div>

                <div class="form_credentials">
                    <div class="input">
                        <label for="comment_email">E-mailadres</label>
                        <input type="email" id="comment_email">
                    </div>
                    <div class="input">
                        <label for="comment_author">Naam</label>
                        <input type="text" id="comment_author">
                    </div>
                </div>

                <div class="input">
                    <label for="comment_comment2">Wat is hierop je reactie?</label>
                    <textarea id="comment_comment2"></textarea>
                </div>

                <button type="submit" class="red button">Plaats reactie</button>
            </form>

            <hr>

            <div class="comment">
                <img class="image" src="photos/marty.jpg" />
                <div class="content">
                    <div class="meta">
                        <span class="author">Marty McFly</span>
                        <span class="divider">&bull;</span>
                        <span class="time">2 hours ago</span>
                    </div>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.
                    <div class="actions">
                        <a href="#" class="reply">Reply</a>
                    </div>

                    <div class="comment">
                        <img class="image" src="photos/drbrown.jpg" />
                        <div class="content">
                            <div class="meta">
                                <span class="author">Dr. Emmett Brown</span>
                                <span class="divider">&bull;</span>
                                <span class="time">3 hours ago</span>
                            </div>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.
                            <div class="actions">
                                <a href="#" class="reply">Reply</a>
                            </div>
                        </div>
                    </div>

                    <div class="comment">
                        <img class="image" src="photos/drbrown.jpg" />
                        <div class="content">
                            <div class="meta">
                                <span class="author">Dr. Emmett Brown</span>
                                <span class="divider">&bull;</span>
                                <span class="time">3 hours ago</span>
                            </div>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.
                            <div class="actions">
                                <a href="#" class="reply">Reply</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <div class="comment">
                <img class="image" src="photos/drbrown.jpg" />
                <div class="content">
                    <div class="meta">
                        <span class="author">Dr. Emmett Brown</span>
                        <span class="divider">&bull;</span>
                        <span class="time">3 hours ago</span>
                    </div>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.
                    <div class="actions">
                        <a href="#" class="reply">Reply</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="three wide column sidebar">
        <?php include 'archivelist.phtml'; ?>
    </div>

    <?php $this->startCapture('scripts', true); ?>
    <script>
    (function () {
        var emailInput, nameInput, commentInput, commenterKeyInput, key, isFetching = false;

        emailInput = document.querySelector('[name="email"]');
        nameInput = document.querySelector('[name="name"]');
        commentInput = document.querySelector('[name="comment"]');
        commenterKeyInput = document.querySelector('[name="commenter_key"]');

        function showLoggedInPart(commenter) {
            commenterKey.value = commenter.id;
            document.getElementById('commenter_name').innerHTML = commenter.name;
            document.getElementById('commenter_email').innerHTML = commenter.email;
            document.querySelector('.form_credentials').style.display = 'none';
            document.querySelector('.form_logged_in').style.display = 'block';
        }

        function hideLoggedInPart() {
            commenterKey.value = '';
            document.querySelector('.form_credentials').style.display = 'block';
            document.querySelector('.form_logged_in').style.display = 'none';
        }

        emailInput.addEventListener('change', function(e) {
            var xhr;

            if (/^[^@]+@([^\.]+\.)+[a-z]{2,10}$/.test(this.value) && !isFetching) {
                xhr = new XMLHttpRequest();
                xhr.onreadystatechange = function () {
                    var result;

                    if (this.readyState == 4) {
                        if (this.status == 200) {
                            result = JSON.parse(this.responseText);
                            if (result) {
                                if (result.found) {
                                    showLoggedInPart(result.commenter);
                                }
                            } else {
                                console.error('Error parsing JSON');
                            }
                        } else {
                            console.error(this.statusText);
                        }
                    }
                }
                xhr.open('get', '/commenter/' + this.value);
                xhr.send();
            }
        });

        if (commenter = localStorage.getItem('commenter')) {
            showLoggedInPart(commenter);
        }

        document.getElementById('change_commenter').addEventListener('click', function (e) {
            e.preventDefault();
            hideLoggedInPart();
        });

        document.getElementById('comment_form').addEventListener('submit', function (e) {
            var data = {};

            e.preventDefault();

            if (commenterKeyInput.value) {
                data.commenter_key = commenterKeyInput.value;
            } else {
                data.email = emailInput.value;
                data.name = nameInput.value;
            }
        });
    });
    </script>
    <?php $this->endCapture(); ?>
</div>
